In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Words of Caution ##
- Remember to run the cell above. It's for setting up the environment so you can have access to what's needed for this lecture. For now, don't worry about what it means: we'll learn more about what's inside of it in the next few lectures.
- Data science is not just about code, so please don't go over this notebook by itself. Have the relevant textbook sections or lecture video at hand so that you can go over the discussion along with the code. Thank you! 

## Python ##

In [ ]:
a = 2 + 9

In [ ]:
a * 3

In [ ]:
2 / 9

In [ ]:
2 + 3 * 9

In [ ]:
(2 + 3) * 9

In [ ]:
# two to the power of four: 2 * 2 * 2 * 2
2 ** 4

In [4]:
print('bye')

print('hello')

bye
hello


## Names ##

In [5]:
a

NameError: name 'a' is not defined

In [6]:
a = 4

In [7]:
a

4

In [8]:
print(a)

4


In [10]:
b = 9
b

9

In [11]:
b

9

In [13]:
c = a * 3

In [17]:
total = c + b
total

21

In [ ]:
total

In [ ]:
a = 10

In [20]:
total four

4

In [ ]:
total = a + b

In [ ]:
total

In [23]:
total = 'total'
total

'total'

### Why Names?

In [ ]:
hours_per_week = 40
weeks_per_year = 52

In [ ]:
hours_per_year = hours_per_week * weeks_per_year

In [ ]:
hours_per_year

In [ ]:
# Minimum wage for businesses w/26 or more employees
# Goes up by $1/hr until 2022
ca_hourly_minimum_wage = 13.00

In [ ]:
weekly_wages = hours_per_week * ca_hourly_minimum_wage
weekly_wages

In [ ]:
yearly_wages = hours_per_year * ca_hourly_minimum_wage
yearly_wages

In [ ]:
40 * 13.00

In [ ]:
40 * 52 * 13.00

## Functions and Call Expressions

In [25]:
a + 2

6

In [28]:
add2 = lambda b: b+2
add2

<function __main__.<lambda>(b)>

In [29]:
add2(a)

6

In [30]:
abs(-5)

5

In [32]:
abs(1 - (5-2))

2

In [ ]:
day_temp = 52
night_temp = 47
abs(night_temp - day_temp)

In [ ]:
min(14, 15)

In [33]:
round(123.456)

123

In [36]:
round(123.456, 2)

123.46

In [ ]:
round(123.456, ndigits=1)

In [35]:
round?

In [44]:
f = lambda b: b+2
f

<function __main__.<lambda>(b)>

In [46]:
def f(b):
    return b+4
f

<function __main__.f(b)>

In [45]:
f(3) + 5

10

## Tables ##

In [64]:
cones = Table.read_table('cones.csv')
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [48]:
cones.show(3)

In [50]:
cones.show?

In [51]:
cones.select('Flavor')

Flavor
strawberry
chocolate
chocolate
strawberry
chocolate
bubblegum

In [67]:
cones2 = cones.select('Flavor', 'Price')
cones2

Flavor     | Price
strawberry | 3.55
chocolate  | 4.75
chocolate  | 5.25
strawberry | 5.25
chocolate  | 5.25
bubblegum  | 4.75

In [59]:
Flavor = "Color"
cones.select(Flavor, 'Price')

Color       | Price
pink        | 3.55
light brown | 4.75
dark brown  | 5.25
pink        | 5.25
dark brown  | 5.25
pink        | 4.75

In [60]:
cones.drop('Price')

Flavor     | Color
strawberry | pink
chocolate  | light brown
chocolate  | dark brown
strawberry | pink
chocolate  | dark brown
bubblegum  | pink

In [61]:
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [63]:
cones_without_price = cones.drop('Price')
cones_without_price

Flavor
strawberry
chocolate
chocolate
strawberry
chocolate
bubblegum

In [69]:
cones2.where('Flavor', 'chocolate')

Flavor    | Price
chocolate | 4.75
chocolate | 5.25
chocolate | 5.25

In [78]:
column_name = 'Price$&^ of the product'
column_name

'Price$&^ of the product'

In [72]:
cones.sort('Price', descending=False)

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
bubblegum  | pink        | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25

In [ ]:
cones.sort('Flavor', descending=True)

### A more interesting table

In [110]:
skyscrapers = Table.read_table('skyscrapers.csv')
skyscrapers

name                              | material  | city          | height | completed
One World Trade Center            | composite | New York City | 541.3  | 2014
Willis Tower                      | steel     | Chicago       | 442.14 | 1974
432 Park Avenue                   | concrete  | New York City | 425.5  | 2015
Trump International Hotel & Tower | concrete  | Chicago       | 423.22 | 2009
Empire State Building             | steel     | New York City | 381    | 1931
Bank of America Tower             | composite | New York City | 365.8  | 2009
Stratosphere Tower                | concrete  | Las Vegas     | 350.22 | 1996
Aon Center                        | steel     | Chicago       | 346.26 | 1973
John Hancock Center               | steel     | Chicago       | 343.69 | 1969
WITI TV Tower                     | steel     | Shorewood     | 329    | 1962
... (190 rows omitted)

In [111]:
skyscrapers.where('city', 'Los Angeles')

name                  | material | city        | height | completed
U.S. Bank Tower       | steel    | Los Angeles | 310.29 | 1990
Aon Center            | steel    | Los Angeles | 261.52 | 1974
Two California Plaza  | steel    | Los Angeles | 228.6  | 1992
Gas Company Tower     | steel    | Los Angeles | 228.3  | 1991
Bank of America Plaza | steel    | Los Angeles | 224.03 | 1975
777 Tower             | steel    | Los Angeles | 221    | 1991
Wells Fargo Tower     | steel    | Los Angeles | 220.37 | 1983
Figueroa at Wilshire  | steel    | Los Angeles | 218.54 | 1989
City National Tower   | steel    | Los Angeles | 213.06 | 1971
Paul Hastings Tower   | steel    | Los Angeles | 213.06 | 1971
... (1 rows omitted)

In [112]:
skyscrapers.where('name', 'Empire State Building')

name                  | material | city          | height | completed
Empire State Building | steel    | New York City | 381    | 1931

In [114]:
skyscrapers.where('city', 'New York City').sort('completed')

name                    | material | city          | height | completed
Metropolitan Life Tower | steel    | New York City | 213.36 | 1909
Woolworth Building      | steel    | New York City | 241.4  | 1913
Chanin Building         | steel    | New York City | 197.8  | 1929
Mercantile Building     | steel    | New York City | 192.6  | 1929
Chrysler Building       | steel    | New York City | 318.9  | 1930
The Trump Building      | steel    | New York City | 282.55 | 1930
One Grand Central Place | steel    | New York City | 205.13 | 1930
Empire State Building   | steel    | New York City | 381    | 1931
Twenty Exchange         | steel    | New York City | 225.86 | 1931
500 Fifth Avenue        | steel    | New York City | 212.45 | 1931
... (63 rows omitted)

In [115]:
skyscrapers.where('city', 'New York City').sort('completed', descending=True)

name                                             | material       | city          | height | completed
432 Park Avenue                                  | concrete       | New York City | 425.5  | 2015
Sky                                              | concrete       | New York City | 206    | 2015
One World Trade Center                           | composite      | New York City | 541.3  | 2014
One57                                            | steel/concrete | New York City | 306.07 | 2014
4 World Trade Center                             | composite      | New York City | 297.73 | 2014
Courtyard & Residence Inn Manhattan/Central Park | concrete       | New York City | 229.62 | 2013
Eight Spruce Street                              | concrete       | New York City | 265.18 | 2011
1 MiMA Tower                                     | concrete       | New York City | 194.55 | 2011
Goldman Sachs Headquarters                       | steel          | New York City | 228.3  | 2010
Langham Place                                    | concrete       | New York City | 192.58 | 2010
... (63 rows omitted)

In [121]:
chicago = skyscrapers.where('city', 'Chicago').drop('city')
chicago

name                              | material       | height | completed
Willis Tower                      | steel          | 442.14 | 1974
Trump International Hotel & Tower | concrete       | 423.22 | 2009
Aon Center                        | steel          | 346.26 | 1973
John Hancock Center               | steel          | 343.69 | 1969
The Franklin - North Tower        | composite      | 306.94 | 1989
Two Prudential Plaza              | concrete       | 303.28 | 1990
311 South Wacker Drive            | concrete       | 292.92 | 1990
900 North Michigan Avenue         | concrete/steel | 265    | 1989
Water Tower Place                 | concrete       | 261.88 | 1976
Aqua                              | concrete       | 261.75 | 2009
... (26 rows omitted)

In [122]:
chicago.where('material', 'steel').sort('completed', descending=True)

name                    | material | height | completed
Willis Tower            | steel    | 442.14 | 1974
Aon Center              | steel    | 346.26 | 1973
John Hancock Center     | steel    | 343.69 | 1969
Chase Tower             | steel    | 259.08 | 1969
Richard J. Daley Center | steel    | 197.51 | 1965

In [124]:
nba = Table.read_table('nba_salaries.csv')
nba

PLAYER           | POSITION | TEAM          | '15-'16 SALARY
Paul Millsap     | PF       | Atlanta Hawks | 18.6717
Al Horford       | C        | Atlanta Hawks | 12
Tiago Splitter   | C        | Atlanta Hawks | 9.75625
Jeff Teague      | PG       | Atlanta Hawks | 8
Kyle Korver      | SG       | Atlanta Hawks | 5.74648
Thabo Sefolosha  | SF       | Atlanta Hawks | 4
Mike Scott       | PF       | Atlanta Hawks | 3.33333
Kent Bazemore    | SF       | Atlanta Hawks | 2
Dennis Schroder  | PG       | Atlanta Hawks | 1.7634
Tim Hardaway Jr. | SG       | Atlanta Hawks | 1.30452
... (407 rows omitted)

In [ ]:
nba = nba.relabeled("'15-'16 SALARY", 'SALARY')

In [135]:

nba.select('SALARY', 'PLAYER').sort('SALARY', descending=True).show(1)

In [136]:
nba.where('TEAM', 'Golden State Warriors').sort('SALARY', descending=False).show(1)

In [138]:
nba.drop('PLAYER').sort('SALARY', descending=True).show(5)

## Numbers ##

In [ ]:
4 * 5 

In [ ]:
20  # int

In [ ]:
20 / 3  # float

In [ ]:
20 / 2  # also a float

In [ ]:
1234 ** 5

In [ ]:
123456789 ** 1234

In [80]:
100/6

16.666666666666668

In [ ]:
4 / 700000000000000000

In [ ]:
0.12345678901234567890123456789

In [ ]:
0.12345678901234567890123456789 - 0.1234567890123456789

In [ ]:
10 ** 0.5

In [ ]:
16 ** 0.5

In [ ]:
(10 ** 0.5) ** 2

In [81]:
20 / 10

2.0

In [82]:
int(20 / 10)

2

In [ ]:
int(20 / 9)

In [83]:
float(3)

3.0

In [ ]:
6 / 4

In [ ]:
6 / 4000

In [ ]:
6 / 400000000000000000000000000000000000000000000000000000000

In [ ]:
400000000000000000000000000000000000000000000000000000000 * 1.5e-56 

In [ ]:
1.5e-56 

In [ ]:
x = 5

In [ ]:
2x

In [ ]:
2 * x

In [ ]:
round(3.7)

In [ ]:
round(2.00000052345324, 2)

In [ ]:
10 * 3.0

## Strings ##

In [84]:
'baby yoda'

'baby yoda'

In [85]:
"baby yoda isn't yoda"

"baby yoda isn't yoda"

In [86]:
'baby yoda isn't yoda'

SyntaxError: invalid syntax (2037818190.py, line 1)

In [87]:
'straw' + 'berry' # concatenation

'strawberry'

In [ ]:
'straw' + ' ' + 'berry'

In [ ]:
'ha' * 10

In [ ]:
'lo' * 5.5

In [88]:
int('3')

3

In [89]:
int('3.0')

ValueError: invalid literal for int() with base 10: '3.0'

In [90]:
float('3.0')

3.0

In [91]:
str(3)

'3'

In [92]:
str(4.5)

'4.5'

In [93]:
x = 3
y = '4'
z = '5.6'


In [94]:
x + y

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [96]:
int(y + z)

ValueError: invalid literal for int() with base 10: '45.6'

In [99]:
str(x, y)

TypeError: decoding to str: need a bytes-like object, int found

In [102]:
'I\'m a data scientist!'

"I'm a data scientist!"

In [109]:
salaries = Table.read_table("nba_salaries.csv")
salaries

PLAYER           | POSITION | TEAM          | '15-'16 SALARY
Paul Millsap     | PF       | Atlanta Hawks | 18.6717
Al Horford       | C        | Atlanta Hawks | 12
Tiago Splitter   | C        | Atlanta Hawks | 9.75625
Jeff Teague      | PG       | Atlanta Hawks | 8
Kyle Korver      | SG       | Atlanta Hawks | 5.74648
Thabo Sefolosha  | SF       | Atlanta Hawks | 4
Mike Scott       | PF       | Atlanta Hawks | 3.33333
Kent Bazemore    | SF       | Atlanta Hawks | 2
Dennis Schroder  | PG       | Atlanta Hawks | 1.7634
Tim Hardaway Jr. | SG       | Atlanta Hawks | 1.30452
... (407 rows omitted)

## Types ##

In [ ]:
type(10)

In [ ]:
a = 10
type(a)

In [ ]:
type(4.5)

In [ ]:
type('abc')

In [ ]:
type(skyscrapers)

In [ ]:
type(True)

In [ ]:
type(abs)

## Arrays ##

In [2]:
my_array = make_array(1, 2, 3, 4)

In [3]:
my_array

array([1, 2, 3, 4])

In [4]:
my_array * 2

array([2, 4, 6, 8])

In [5]:
my_array ** 2

array([ 1,  4,  9, 16])

In [6]:
my_array + 1

array([2, 3, 4, 5])

In [ ]:
my_array # array is unchanged

In [7]:
len(my_array)

4

In [8]:
sum(my_array)

10

In [9]:
len(my_array) / sum(my_array)

0.4

In [10]:
another = make_array(60, 70, 80, 90)

In [11]:
my_array + another

array([61, 72, 83, 94])

In [12]:
yet_another = make_array(5, 6, 7)

In [13]:
my_array + yet_another

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [14]:
tunas = make_array('bluefin', 'albacore', 'jim')
tunas

array(['bluefin', 'albacore', 'jim'], dtype='<U8')

In [ ]:
sum(my_array)

In [ ]:
np.average(my_array)

In [ ]:
len(my_array)

## Columns of Tables are Arrays ##

In [ ]:
sf = skyscrapers.where('city', 'San Francisco')
sf

In [ ]:
sf.select('height')

In [ ]:
sf.column('height')

In [ ]:
np.average(sf.column('height'))

In [ ]:
la = skyscrapers.where('city', 'Los Angeles')

In [ ]:
np.average(la.column('height')) - np.average(sf.column('height'))

## Arrays

In [ ]:
heights = make_array(67, 60, 71, 63, 65)
heights

In [ ]:
heights / 12

In [ ]:
len(heights)

In [ ]:
sum(heights)

In [ ]:
sum(heights) / len(heights)

In [ ]:
np.average(heights)

In [ ]:
strings_array = make_array('ok', 'ya', 'hm')
strings_array

In [ ]:
strings_array * 2

In [ ]:
heights.item(3)

In [ ]:
heights.item(0)

In [ ]:
strings_array.item(0)

## Ranges ##

In [15]:
make_array(0, 1, 2, 3, 4, 5, 6)

array([0, 1, 2, 3, 4, 5, 6])

In [16]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [17]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [18]:
np.arange(5, 11)

array([ 5,  6,  7,  8,  9, 10])

In [22]:
np.arange(0, -20, -2)

array([  0,  -2,  -4,  -6,  -8, -10, -12, -14, -16, -18])

In [20]:
np.arange(0, 21, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [23]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [ ]:
a = np.arange(8)

In [ ]:
a

In [ ]:
a.item(8)

## Creating a Table from Scratch ##

In [ ]:
streets = make_array('Bancroft', 'Durant', 'Channing', 'Haste')
streets

In [ ]:
Table()

In [ ]:
southside = Table().with_column('Streets', streets)
southside

In [ ]:
southside.with_column('Blocks from campus', np.arange(4))

In [ ]:
southside

In [ ]:
southside = southside.with_column('Blocks from campus', np.arange(4))
southside

In [ ]:
southside.labels

In [ ]:
southside.num_columns

In [ ]:
southside.num_rows

## Reading a Table from a File  ##

In [ ]:
du_bois = Table.read_table('du_bois.csv')
du_bois

In [ ]:
# Which group ("CLASS") spent the highest percentage on rent?
...

In [ ]:
du_bois.select('STATUS')

In [ ]:
du_bois.column('STATUS')

In [ ]:
du_bois.select('STATUS')

In [ ]:
du_bois.column('STATUS')

In [ ]:
du_bois.column('ACTUAL AVERAGE')

In [ ]:
du_bois.column('FOOD')

In [ ]:
du_bois.column('ACTUAL AVERAGE') * du_bois.column('FOOD')

In [ ]:
food_dollars = du_bois.column('ACTUAL AVERAGE') * du_bois.column('FOOD')
du_bois = du_bois.with_column(
    'Food $',
    food_dollars
)
du_bois

In [ ]:
du_bois.set_format('FOOD', PercentFormatter)

In [ ]:
du_bois.select('CLASS', 'ACTUAL AVERAGE', 'FOOD', 'Food $')

In [ ]:
du_bois.column('FOOD')

## Selecting data in a column ##

In [ ]:
movies = Table.read_table('movies_by_year_with_ticket_price.csv')
movies.show()

In [ ]:
gross_in_dollars = movies.column('Total Gross') * 1e6
tix_sold = gross_in_dollars / movies.column('Average Ticket Price')

In [ ]:
movies = movies.with_column('Tickets sold', tix_sold)

In [ ]:
movies.show(4)

In [ ]:
movies.set_format('Tickets sold', NumberFormatter)

In [ ]:
movies.plot('Year', 'Tickets sold')

In [ ]:
movies.where('Year', are.between(2000, 2005))

In [ ]:
movies.where('Year', 2002)

In [ ]:
movies.where('Year', are.equal_to(2002))

In [ ]:
movies.where('#1 Movie', are.containing('Harry Potter'))

In [ ]:
movies.take(np.arange(2, 5))

# My notes

In [31]:
courses = Table()

In [32]:
courses = courses.with_column("CS Courses", make_array("SE", "Web", "Java"))

In [36]:
courses = courses.relabeled(0, "Course")

In [37]:
courses

Course
SE
Web
Java

In [39]:
courses_with_credit = courses.with_column("Credits", make_array(4,2,5))
courses_with_credit

Course | Credits
SE     | 4
Web    | 2
Java   | 5

In [43]:
courses_with_credit.column(1)

array([4, 2, 5])

In [49]:
np.average(courses_with_credit.column("Credits"))

3.6666666666666665

In [52]:
credits = courses_with_credit.column("Credits")
credits

array([4, 2, 5])

In [55]:
sum_of_credits = sum(credits)
sum_of_credits

11

In [58]:
credits / sum_of_credits

array([0.36363636, 0.18181818, 0.45454545])

In [63]:
credits = courses_with_credit.column("Credits")
sum_of_credits = sum(credits)

props = courses_with_credit.with_column("Proportion", credits / sum_of_credits)
props

Course | Credits | Proportion
SE     | 4       | 0.363636
Web    | 2       | 0.181818
Java   | 5       | 0.454545

In [70]:
avg_credits = np.average(credits)
table2 = props.with_column("Average", make_array(avg_credits,avg_credits,avg_credits))
table2.labels

('Course', 'Credits', 'Proportion', 'Average')

In [75]:
table2.take(np.arange(1, table2.num_rows, 2))

Course | Credits | Proportion | Average
Web    | 2       | 0.181818   | 3.66667

In [83]:
table2

Course | Credits | Proportion | Average
SE     | 4       | 0.363636   | 3.66667
Web    | 2       | 0.181818   | 3.66667
Java   | 5       | 0.454545   | 3.66667

In [85]:
credit_avg = np.average(table2.column("Credits"))
table2.where('Course', are.not_containing('ava'))

Course | Credits | Proportion | Average
SE     | 4       | 0.363636   | 3.66667
Web    | 2       | 0.181818   | 3.66667

#### Census workout

In [106]:
census = Table.read_table('nc-est2014-agesex-res.csv')
census2 = census.select('SEX', 'AGE', 'POPESTIMATE2010', 'POPESTIMATE2013').relabeled(2, '2010').relabeled(3, '2013')
census3 = census2.where('AGE',are.between(0,12))
census3

SEX  | AGE  | 2010    | 2013
0    | 0    | 3951330 | 3945610
0    | 1    | 3957888 | 3943077
0    | 2    | 4090862 | 3992690
0    | 3    | 4111920 | 3992425
0    | 4    | 4077552 | 3994047
0    | 5    | 4064653 | 4123408
0    | 6    | 4073013 | 4143094
0    | 7    | 4043047 | 4108615
0    | 8    | 4025604 | 4095827
0    | 9    | 4125415 | 4104133
... (26 rows omitted)

In [107]:
census4 = census3.with_column("Increase", (census3.column('2013') - census3.column('2010')) / census3.column('2010'))
census4

SEX  | AGE  | 2010    | 2013    | Increase
0    | 0    | 3951330 | 3945610 | -0.00144761
0    | 1    | 3957888 | 3943077 | -0.00374215
0    | 2    | 4090862 | 3992690 | -0.0239979
0    | 3    | 4111920 | 3992425 | -0.0290606
0    | 4    | 4077552 | 3994047 | -0.0204792
0    | 5    | 4064653 | 4123408 | 0.0144551
0    | 6    | 4073013 | 4143094 | 0.0172062
0    | 7    | 4043047 | 4108615 | 0.0162175
0    | 8    | 4025604 | 4095827 | 0.0174441
0    | 9    | 4125415 | 4104133 | -0.00515875
... (26 rows omitted)

In [108]:
census4.set_format('Increase', PercentFormatter)

SEX  | AGE  | 2010    | 2013    | Increase
0    | 0    | 3951330 | 3945610 | -0.14%
0    | 1    | 3957888 | 3943077 | -0.37%
0    | 2    | 4090862 | 3992690 | -2.40%
0    | 3    | 4111920 | 3992425 | -2.91%
0    | 4    | 4077552 | 3994047 | -2.05%
0    | 5    | 4064653 | 4123408 | 1.45%
0    | 6    | 4073013 | 4143094 | 1.72%
0    | 7    | 4043047 | 4108615 | 1.62%
0    | 8    | 4025604 | 4095827 | 1.74%
0    | 9    | 4125415 | 4104133 | -0.52%
... (26 rows omitted)